name: rx_image_search
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cached_network_image: ^3.1.0+1
  cupertino_icons: ^1.0.2
  dio: ^4.0.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_dotenv: ^5.0.2
  flutter_staggered_grid_view: ^0.4.1
  google_fonts: ^2.1.0
  image_gallery_saver: ^1.7.1
  permission_handler: ^8.3.0
  rive: ^0.7.33
  shimmer: ^2.0.0
dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/
    - assets/animations/
    - assets/images/
